---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes