---
# handlers file for hardening
- name: Restart resolvectl
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart NetworkManager
  become: true
  ansible.builtin.service:
    name: NetworkManager
    state: restarted

- name: Applying Kernel parameters
  become: true
  ansible.builtin.command:
    cmd: sysctl --system
  register: sysctl_output
  changed_when: "'Applying /etc/sysctl.d/99-sysctl-lynis.conf' in sysctl_output.stdout"

- name: Restart firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: Restart fail2ban
  become: true
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
  loop:
    - fail2ban
    - firewalld

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
