---
- name: Start firewalld service
  become: true
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Enable basic firewall rules
  become: true
  ansible.posix.firewalld:
    port: "{{ item.port }}"
    state: "{{ item.state }}"
    immediate: true
    permanent: true
  notify: Restart firewalld
  loop:
    - { port: 10888/tcp, state: enabled }
