---
- name: Update apt cache (for Debian/Ubuntu)
  become: true
  ansible.builtin.apt:
    name:
      - needrestart
      - apt-listchanges
      - libpam-tmpdir
      - debsums
      - unattended-upgrades
      - apt-show-versions
      - lynis
      - fail2ban
      - python3-systemd
      - firewalld
      - chrony
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'  # Conditional task for Debian/Ubuntu systems

- name: Upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    autoremove: true

- name: Setting up ntp
  ansible.builtin.import_tasks: ntp.yml
  tags: ntp

- name: Configuring ssh
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Configuring sysctl
  ansible.builtin.import_tasks: sysctl.yml
  tags: sysctl

- name: Configuring firewalld
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall

- name: Configuring DNS
  ansible.builtin.import_tasks: dns.yml
  tags: dns

- name: Fail2ban
  ansible.builtin.import_tasks: fail2ban.yml
  tags: fail2ban

- name: Lynis suggestions
  ansible.builtin.import_tasks: lynis-suggestions.yml
  tags: suggestions

- name: Lynis
  ansible.builtin.import_tasks: lynis.yml
  tags: lynis
