- name: Check Service ntp being started
  become: true
  ansible.builtin.systemd_service:
    name: chrony
    state: started
    enabled: true

- name: Set time-zone to Asia/Tehran
  become: true
  community.general.timezone:
    name: Asia/Tehran
